filter-semver-tag: &filter-semver-tag
  tags:
    only: /^(major|minor|patch)-v\d+\.\d+\.\d+$/

version: 2.1

orbs:
  grype: anchore/grype@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

parameters:
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

workflows:
  lint-test-and-publish:
    jobs:
      - orb-tools/lint:
        filters: *filter-semver-tag
      - orb-tools/pack:
          filters: *filter-semver-tag
      - shellcheck/check:
          filters: *filter-semver-tag
          dir: ./src/scripts
          exclude: SC2148
      - bats/run:
          filters: *filter-semver-tag
          path: ./src/tests
      - grype/list-image-vulns:
          filters: *filter-semver-tag
          image-name: ubuntu:20.04
      - grype/list-dir-vulns:
          filters: *filter-semver-tag
          path-to-scan: ./
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          filters: *filter-semver-tag
          orb-name: anchore/grype
          context: publish_dev_orb # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
            - grype/list-image-vulns
            - grype/list-dir-vulns
      - hold-for-approval:
          type: approval
          filters: *filter-semver-tag
          requires:
            - orb-tools/publish-dev
      - orb-tools/dev-promote-prod-from-git-tag:
          filters: *filter-semver-tag
          add-pr-comment: false
          orb-name: anchore/grype
          context: publish_prod_orb
          requires:
            - hold-for-approval
